#IMAGE_INSTALL_append = " greengrass"
IMAGE_INSTALL_append = " aws-greengrass-core-sdk-python aws-greengrass-core-sdk-c"
IMAGE_INSTALL_append = " mosquitto"
IMAGE_INSTALL_append = " awsapp"
IMAGE_INSTALL_append = " aws-iot-device-sdk-cpp aws-iot-device-sdk-cpp-dev aws-iot-device-sdk-cpp-samples"
IMAGE_INSTALL_append = " valgrind"
