/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "<AWS cognito user pool region>",
    "aws_cognito_identity_pool_id": "<AWS cognito identity pool id>",
    "aws_cognito_region": "<AWS cognito region>",
    "aws_user_pools_id": "<AWS user pool id>",
    "aws_user_pools_web_client_id": "<AWS pool web client id>",
    "oauth": {}
};


export default awsmobile;
