
export const SET_FACILITIES = "SET_FACILITIES";

export const SET_CONTAINERS = "SET_CONTAINERS";
export const SET_CONTAINERS_BY_FACILITY_ID = "SET_CONTAINERS_BY_FACILITY_ID";

export const SET_GROWAREAS = "SET_GROWAREAS";
export const SET_GROWAREAS_BY_CONTAINER_ID = "SET_GROWAREAS_BY_CONTAINER_ID";
export const SET_GROWAREA_TYPES = "SET_GROWAREA_TYPES";
export const SET_COUNT_BY_GROWAREA_ID = "SET_COUNT_BY_GROWAREA_ID";

export const SET_GROWSECTIONS = "SET_GROWSECTIONS";
export const SET_GROWSECTIONS_BY_GROWAREA_ID = "SET_GROWSECTIONS_BY_GROWAREA_ID";

export const SET_DEVICES = "SET_DEVICES";
export const SET_DEVICES_BY_GROWSECTION_ID = "SET_DEVICES_BY_GROWSECTION_ID";
export const SET_DEVICES_BY_GROWAREA_ID = "SET_DEVICES_BY_GROWAREA_ID";
export const SET_DEVICE_TYPES = "SET_DEVICE_TYPES";

export const UI_START_LOADING = "UI_START_LOADING";
export const UI_STOP_LOADING = "UI_STOP_LOADING";
export const COUNT_UI_START_LOADING = "COUNT_UI_START_LOADING";
export const COUNT_UI_STOP_LOADING = "COUNT_UI_STOP_LOADING";
export const UI_REGISTRATION_PROCESS = "UI_REGISTRATION_PROCESS";
export const UI_START_LOADING_INDEVICE = "UI_START_LOADING_INDEVICE"

export const SET_USERS = "SET_USERS";
export const SET_USERS_BY_FACILITY_ID = "SET_USERS_BY_FACILITY_ID";
export const SET_USER_DETAILS = "SET_USER_DETAILS";

export const SENDING_PAYLOAD_TO_GATEWAY = "SENDING_PAYLOAD_TO_GATEWAY";

export const REGISTERED_DEVICE_COUNT = "REGISTERED_DEVICE_COUNT";

export const AUTH_SET_USER = "AUTH_SET_USER";
export const AUTH_REMOVE_USER = "AUTH_REMOVE_USER";
export const USER_LOGOUT = 'USER_LOGOUT';

export const REGISTER_GATEWAY_TO_ARROW = "REGISTER_GATEWAY_TO_ARROW";
export const REGISTER_GATEWAY = "REGISTER_GATEWAY";
export const SET_GATEWAY_HID = "SET_GATEWAY_HID";
export const SET_GATEWAY_KEYS = "SET_GATEWAY_KEYS";

export const GET_ALL_GATEWAYS = "GET_ALL_GATEWAYS";
export const GET_BLE_DEVICES = "GET_BLE_DEVICES";
export const ADD_BLE_DEVICE = "ADD_BLE_DEVICE";
export const GET_BLE_MANAGER = "GET_BLE_MANAGER";
export const SET_BLE_MANAGER = "SET_BLE_MANAGER";
export const REMOVE_BLE_DEVICE = "REMOVE_BLE_DEVICE";
export const REMOVE_BLE_DEVICE_SIGNOUT_FROM_DEVICE = 'REMOVE_BLE_DEVICE_SIGNOUT_FROM_DEVICE';
export const REMOVE_BLE_DEVICE_SIGNOUT_FROM_GROWAREA = 'REMOVE_BLE_DEVICE_SIGNOUT_FROM_GROWAREA';
export const DELETE_GATEWAY = 'DELETE_GATEWAY';
export const DELETE_DEVICES = 'DELETE_DEVICES';

export const GET_HISTORICAL_DATA = "GET_HISTORICAL_DATA";
export const GET_DEVICE_PROPERTY = "GET_DEVICE_PROPERTY";

export const GET_LED_PROFILE = "GET_LED_PROFILE";
export const GET_LEDCHANNEL_DATA = "GET_LEDCHANNEL_DATA";
export const SET_LEDCHANNEL_DATA = "SET_LEDCHANNEL_DATA";
export const GET_CURRENT_VALUE_OF_LEDNODE = 'GET_CURRENT_VALUE_OF_LEDNODE'
export const SET_LED_INTENCITY = "SET_LED_INTENCITY";
export const GET_RECENT_DATA = 'GET_RECENT_DATA';
export const CLEAR_CURRENT_DATA = 'CLEAR_CURRENT_DATA';

export const GET_LEDNODE_GROUP_LIST = 'GET_LEDNODE_GROUP_LIST';
export const IS_LED_GROUP_LIST_LOADING = 'IS_LED_GROUP_LIST_LOADING';

export const GET_LEDNODE_GROUP_PROFILE_LIST = 'GET_LEDNODE_GROUP_PROFILE_LIST';
export const FIND_LEDNODE_FOR_GROUP = 'FIND_LEDNODE_FOR_GROUP';
export const FIND_DEVICES_LOADER = 'FIND_DEVICES_LOADER';
export const GROUPE_LIST_PROCEESSING = 'GROUPE_LIST_PROCEESSING';
export const IS_LED_GROUP_INDIVIDUAL_GROUP_LOADING = 'IS_LED_GROUP_INDIVIDUAL_GROUP_LOADING';
export const GET_GROUP_DETAILS = 'GET_GROUP_DETAILS'

export const IS_LED_GROUP_PROFILE_LIST_LOADING = 'IS_LED_GROUP_PROFILE_LIST_LOADING';
export const PROFILE_LIST_PROCEESSING = 'PROFILE_LIST_PROCEESSING';
export const GET_GROUP_PROFILE_DETAILS = 'GET_GROUP_PROFILE_DETAILS';
export const IS_GROUP_PROFILE_DETAILS_LOADING = 'IS_GROUP_PROFILE_DETAILS_LOADING';
export const IS_LED_PROFILE_DELETED = 'IS_LED_PROFILE_DELETED';

export const GET_EVENT_LIST = 'GET_EVENT_LIST';
export const IS_EVENT_LOADING = 'IS_EVENT_LOADING';
export const EVENT_LIST_PROCEESSING = 'EVENT_LIST_PROCEESSING';
export const OCCURED401 = 'OCCURED401';
export const RESET401 = 'RESET401';

